// app/layout.tsx
import type { Metadata } from "next"
import "../styles/globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { Inter } from "next/font/google"
import { Toaster } from "sonner"

export const metadata: Metadata = {
  title: "E X T",
  description: "Generated by create next app",
}

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
})

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning className={inter.variable}>
      {/* Use your design tokens via Tailwind utilities */}
      <body className="bg-background text-foreground font-sans antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}

          {/* Sonner toaster – picks up light/dark from ThemeProvider */}
          <Toaster richColors closeButton position="top-right" theme="system" />
        </ThemeProvider>
      </body>
    </html>
  )
}
